name: '@actalog/mongodump'
description: Creates a binary export of a database's contents
branding:
  icon: 'database'
  color: 'green'

inputs:
  connection-string:
    required: true
  output-password:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.connection-string }}
    - ${{ inputs.output-password }}
