name: Mongodump Action
description: GitHub Action for creating a binary export of a database's contents

inputs:
  connection-string:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.connection-string }}

branding:
  icon: 'database'
  color: 'green'
