name: CI

on:
  - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      database:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          connection-string: mongodb://database:27017
      - uses: actions/upload-artifact@v3
        with:
          name: dump
          path: ${{ github.workspace }}/dump
